services:
  db:
    image: postgres:17
    container_name: indexer-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    shm_size: 1gb
    ports:
      - "${DB_PORT}:${DB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - indexer-network
  indexer:
    build: .
    container_name: indexer-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: ${DB_DOCKER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GATEWAY_URL: ${GATEWAY_URL}
      RPC_ENDPOINT: ${RPC_ENDPOINT}
      START_BLOCK: ${START_BLOCK}
      RATE_LIMIT: ${RATE_LIMIT}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      GRAPHQL_PORT: ${GRAPHQL_PORT}
    restart: unless-stopped
    networks:
      - indexer-network
  graphql:
    build: .
    container_name: indexer-graphql
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: ${DB_DOCKER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GQL_PORT: ${GRAPHQL_PORT}
    ports:
      - "${GRAPHQL_PORT}:${GRAPHQL_PORT}"
    command: ["npx", "squid-graphql-server"]
    restart: unless-stopped
    networks:
      - indexer-network
      - shared-network

volumes:
  postgres_data:


networks:
  indexer-network:
  shared-network:
    name: agroasys-shared-network